### ISSUE TITLE
maxTextLength的设置如果是在textRestrict的设置之后会出现bug

### ISSUE THREAD

**Issue by shafujiu** [sindrilin/LXDTextFieldAdjust#1]
maxTextLength的设置如果是在textRestrict的设置之后，长度的限制就没有作用了。原因应该是这样，对文本框的限制是通过LXDTextRestrict类来实现的，这里面做的长度限制的控制，如果你在设置textRestrict属性的时候它并没有拿到UITextField的maxTextLength的值。所以限制的长度人就是初始值NSUIntegerMax。
解决办法就是，在分类里面setMaxTextLength方法里面再设置一下textRestrict，也许考虑不够全面。。。

**Comment by sindrilin** [comment]
好的，后续看下如何改进
